using Microsoft.Maui.Controls;

namespace Parcial13_GaleriaMusical;

public partial class App : Application
{
    public static bool IsDarkMode { get; private set; } = false;

    public App()
    {
        InitializeComponent(); // ✅ Generated by XAML
        MainPage = new AppShell();
    }

    public static void ToggleTheme()
    {
        var app = (App)Current;
        var resources = app.Resources;

        if (IsDarkMode)
        {
            // → Light
            resources.MergedDictionaries.Clear();
            resources.MergedDictionaries.Add(new Parcial13_GaleriaMusical.Resources.Styles.LightTheme());
            IsDarkMode = false;
        }
        else
        {
            // → Dark
            resources.MergedDictionaries.Clear();
            resources.MergedDictionaries.Add(new Parcial13_GaleriaMusical.Resources.Styles.DarkTheme());
            IsDarkMode = true;
        }
    }
}